# Generated by Django 5.2.5 on 2025-11-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_alter_projectimage_image_alter_projectvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='video',
            field=models.FileField(upload_to='project_video/'),
        ),
    ]
