# Generated by Django 5.2.5 on 2025-10-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_projectcomment_projectlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('fullstack', 'Fullstack'), ('django', 'Django'), ('react', 'React'), ('opencv', 'OpenCv'), ('ai', 'AI'), ('miniprojects', 'MiniProjects'), ('learning', 'Learning')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_spent',
            field=models.CharField(blank=True, help_text="Example: '2 weeks', '30 hours'", max_length=100, null=True),
        ),
    ]
