# Generated by Django 5.2.5 on 2025-10-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_project_project_type_alter_project_time_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
