# Generated by Django 5.2.5 on 2025-11-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_alter_projectimage_image_alter_projectvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linkedin_link',
            field=models.URLField(blank=True, help_text='Project LinkedIn post or profile link', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube video link for project demo', null=True),
        ),
    ]
