# Generated by Django 5.2.5 on 2025-11-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_project_linkedin_link_project_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='media',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
