# Generated by Django 5.2.5 on 2025-11-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_remove_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
