# Generated by Django 5.2.5 on 2025-11-10 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_projectcomment_media_alter_projectcomment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCustomLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_links', to='myportfolio.project')),
            ],
        ),
    ]
