# Generated by Django 5.2.5 on 2025-11-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0007_projectbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
