# Generated by Django 5.2.5 on 2025-11-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0007_projectcustomlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('fullstack', 'Fullstack'), ('django', 'Django'), ('react', 'React'), ('opencv', 'OpenCv'), ('ai', 'AI'), ('html', 'HTML'), ('miniprojects', 'MiniProjects'), ('learning', 'Learning')], max_length=20, null=True),
        ),
    ]
