# Generated by Django 5.2.5 on 2025-11-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0008_journeymilestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeymilestone',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='JourneyAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Achievements', to='myportfolio.journeymilestone')),
            ],
        ),
    ]
