# Generated by Django 5.2.5 on 2025-11-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0008_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='linkedin_link',
            field=models.URLField(blank=True, help_text='Project LinkedIn post or profile link', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma-separated technologies', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube video link for project demo', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectcustomlink',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectcustomlink',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
