# Generated by Django 5.2.5 on 2025-11-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0009_alter_journeymilestone_title_journeyachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyachievement',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='journeymilestone',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='journeymilestone',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
